### ISSUE TITLE
git clone not working

### ISSUE THREAD

**Issue by jeromew** [pugjs/is-expression-babylon#1]
When I try to use this module, or install it via NPM, it does not seem to work.

it complains with

`Error: Cannot find module 'babylon/lib/parser'`

when I look into the babylon install, this module does not seem to be available.

This is probably related with https://github.com/babel/babylon/commit/beb8db62646081a88b8db31fe95d4b37aa28d98f that migrates bundling to rollup.

**Comment by ForbesLindesay** [comment]
We could submit a pull request to add a `parseExpression` method to babylon's export.

I think we should also think about how we avoid parsing the expressions multiple times once we move to babel-code-gen.  This probably means attaching parsed expressions to the tokens & AST.

**Comment by TimothyGu** [comment]
Yeah unfortunately that seems to be the only way to move forward.

**Comment by jeromew** [comment]
@ForbesLindesay I don't understand what you mean by 

>  think we should also think about how we avoid parsing the expressions multiple times once we move to babel-code-gen. This probably means attaching parsed expressions to the tokens & AST.

In my understanding, once an expression is transformed into AST and added to the AST tree in code gen, it is not reparsed. Or do you mean keeping a cache of parsed expressions in case the come up frequently ?

**Comment by TimothyGu** [comment]
I think he meant the Pug AST, so every `Code` or `InterpolatedCode` node will have a Babylon AST attached to it.

**Comment by jeromew** [comment]
For info I created https://github.com/babel/babylon/issues/210 to ask babylon's maintainers if they think this module's internals is the best approach for the most efficient `parseExpression`

**Comment by ForbesLindesay** [comment]
Yes, I meant the pug ast.  We parse the js expressions in the pug lexer to verify that they are valid JavaScript.  It feels a little bit wrong that we then re-parse them to decide if they are constant using constantinople in pug-code-gen and then parse them yet again in pug-code-gen in order to generate the output AST.

**Comment by jeromew** [comment]
Oh I understand. if the pug-lexer already has the AST (or can be modified to have the AST) we should definitely use this :-). I also agree on constantinople.

**Comment by jeromew** [comment]
Created a new PR https://github.com/babel/babylon/pull/213 with a parseExpression method on babylon. @TimothyGu can you confirm it would allow to do what you had in mind with `is-babylon-expression` ?
